Hello Microverse Linter and Project Setup
ohyajk/HelloMicroverse pull request #1
Opened 2022-10-25 17:01 UTC by ohyajk

I added Linters in the main branch and created an additional branch for HTML & CSS files.

2022-10-25 17:33 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @ohyajk, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 17:33 UTC, bobb-Rob commented on README.md
> +
- [x] I notice that your linter checks are not running as Github actions on this pull request. kindly ensure that linter checks are running on GitHub as expected. Kindly fix that and resubmit.

2022-10-25 17:44 UTC, ohyajk commented on README.md
> +
@bobb-Rob Linter show 4 green ticks. I don't understand what are you trying to say. can you show a youtube video of error?
![linters](https://user-images.githubusercontent.com/114587346/197844897-372e986c-ac52-4e31-8be5-53371d0b6dde.png)

2022-10-26 04:51 UTC, Lameck1 reviewed
Hello, @ohyajk 👋,

_This is an additional review as a result of the second opinion request._

It is true that GitHub actions are not running. The screenshots below verify this:

| This first screenshot shows that 0 checks ran in your last commit |
| --- |
| ![Screenshot 2022-10-26 071841](https://user-images.githubusercontent.com/45002654/197933994-8576c564-3856-4191-a2b0-478e7387e524.png) | 

| This second screenshot shows that there is no green checkmark in the last commit, therefore, no checks ran |
| --- |
| ![Screenshot 2022-10-26 072500](https://user-images.githubusercontent.com/45002654/197934367-5f71657f-6da5-4dc8-aa1f-0e97cff1feca.png) |

In code reviews, it is only the last commit that is considered. Your linter check must be running all the time. In this case, I suspect that the GitHub workflow for this repo must have been disabled. [Please go through this guide and learn how you can reenable the workflows](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#:~:text=workflow%20can%20run.-,Managing%20GitHub%20Actions%20permissions%20for%20your%20repository,Click%20Save.,-Allowing%20select%20actions).

One more thing that @bobb-Rob failed to point out is your commit messages.

  **_If you want to write a git commit message properly, you should use the imperative mood. This means you need to eliminate the temptation to use gerunds or past tense in your subject lines. Don't write a git commit subject line that talks about what you did, or what you are doing. Instead, describe what was done._**
    
  Another rule for commit messages:    
  - The first word must be capitalized. For example, instead of **"add readme"**, it should be **"Add readme"**. Besides this, the message should be meaningful. Referring to your own commit message, instead of writing **"html add"**, you should have written **"Add HTML"**. HTML is an acronym and should be in all UPPERCASE. Your second commit message should have been **"Add CSS"**. Your last commit message could have been **"Update Readme"**
  
  [Consider reading this 2015 article on commit messages](https://www.codelord.net/2015/03/16/bad-commit-messages-hall-of-shame/#:~:text=%E2%80%9Cbug%20fix%E2%80%9D%2C%20%E2%80%9Cmore,well%20supply%20no%20commit%20message.), it is relevant and can help.
  

Please enable GitHub action in this repo, ensure all linters are running and are green, then ask for another code review.

Keep rocking 🚀!

2022-10-26 05:40 UTC, ohyajk commented
I done as the link say which you provided but green tick is not showing. You are not helping me

2022-10-26 05:40 UTC, ohyajk commented
just wasting my reviews

2022-10-26 05:52 UTC, closed without merging